{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n",
      "10\n",
      "11\n",
      "12\n",
      "13\n",
      "14\n",
      "15\n",
      "16\n",
      "17\n",
      "18\n",
      "19\n",
      "20\n",
      "21\n",
      "22\n",
      "23\n",
      "24\n",
      "25\n",
      "26\n",
      "27\n",
      "28\n",
      "29\n",
      "30\n",
      "31\n",
      "32\n",
      "33\n",
      "34\n",
      "35\n",
      "36\n",
      "37\n",
      "38\n",
      "39\n",
      "40\n",
      "41\n",
      "42\n",
      "43\n",
      "44\n",
      "45\n",
      "46\n",
      "47\n",
      "48\n",
      "49\n",
      "50\n",
      "51\n",
      "52\n",
      "53\n",
      "54\n",
      "55\n",
      "56\n",
      "57\n",
      "58\n",
      "59\n",
      "60\n",
      "61\n",
      "62\n",
      "63\n",
      "64\n",
      "65\n",
      "66\n",
      "67\n",
      "68\n",
      "69\n",
      "70\n",
      "71\n",
      "72\n",
      "73\n",
      "74\n",
      "75\n",
      "76\n",
      "77\n",
      "78\n",
      "79\n",
      "80\n",
      "81\n",
      "82\n",
      "83\n",
      "84\n",
      "85\n",
      "STOP THE POD\n"
     ]
    }
   ],
   "source": [
    "#ALL MEASUREMENTS ARE MEANT FOR M/S, NOTHING ELSE\n",
    "track_length =  #Enter track length in meters\n",
    "extra_track =  #Enter how much track you want left at the end of the run\n",
    "velocity =  #VELOCITY BEING READ FROM ODOMOTRY, MATCH WITH FAITH'S CODe\n",
    "position =  #POSITION BEING READ FROM ODOMOTRY, MATCH WITH FAITH'S CODE\n",
    "deceleration =  #ENTER THE DECELERATION OF THE POD (INCLUDE THE - SIGN )\n",
    "\n",
    "    stop_distance = ((-(velocity)**2)/deceleration) + (((velocity)**2)/(2*deceleration))\n",
    "\n",
    "    if ((track_length - extra_track - stop_distance) <= position):\n",
    "        print(\"STOP THE POD\")\n",
    "        motor_speed = 0\n",
    "        kit.servo[0].angle = motor_speed #MOTOR_SPEED MUST BE IN DEGREES FROM 0-180\n",
    "        kit.servo[1].angle = motor_speed\n",
    "        kit.servo[2].angle = motor_speed\n",
    "        kit.servo[3].angle = motor_speed\n",
    "        kit.servo[4].angle = motor_speed\n",
    "        kit.servo[5].angle = motor_speed\n",
    "        kit.servo[6].angle = motor_speed\n",
    "        kit.servo[7].angle = motor_speed\n",
    "        #SET MOTOR SPEEDS TO 0\n",
    "        running = False\n",
    "        break\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
